### ISSUE TITLE
error when trying to train model

### ISSUE THREAD

**Issue by tkhunkhe** [jthurst3/MemeCaptcha#9]
```
InvalidArgumentError (see above for traceback): indices[0,4] = 39344 is not in [0, 20000)
	 [[Node: seq_embedding/embedding_lookup = Gather[Tindices=DT_INT64, Tparams=DT_FLOAT, _class=["loc:@seq_embedding/map"], validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](seq_embedding/map/read, batch_and_pad:1)]]
```
I tried chaning MIN_WORD_COUNT back to 4 and regenerating word_count.txt and TFRecords, but I still get this error

**Comment by tkhunkhe** [comment]
The entire error 
```
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, indices[0,4] = 39344 is not in [0, 20000)
	 [[Node: seq_embedding/embedding_lookup = Gather[Tindices=DT_INT64, Tparams=DT_FLOAT, _class=["loc:@seq_embedding/map"], validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](seq_embedding/map/read, batch_and_pad:1)]]

Caused by op u'seq_embedding/embedding_lookup', defined at:
  File "/gpfs/fs2/scratch/tkhunkhe/MemeCaptcha/models_cnn_lstm/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 117, in <module>
    tf.app.run()
  File "/software/python/2.7.12/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/gpfs/fs2/scratch/tkhunkhe/MemeCaptcha/models_cnn_lstm/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 67, in main
    model.build()
  File "/gpfs/fs2/scratch/tkhunkhe/MemeCaptcha/models_cnn_lstm/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/show_and_tell_model.py", line 355, in build
    self.build_seq_embeddings()
  File "/gpfs/fs2/scratch/tkhunkhe/MemeCaptcha/models_cnn_lstm/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/show_and_tell_model.py", line 226, in build_seq_embeddings
    seq_embeddings = tf.nn.embedding_lookup(embedding_map, self.input_seqs)
  File "/software/python/2.7.12/lib/python2.7/site-packages/tensorflow/python/ops/embedding_ops.py", line 111, in embedding_lookup
    validate_indices=validate_indices)
  File "/software/python/2.7.12/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1359, in gather
    validate_indices=validate_indices, name=name)
  File "/software/python/2.7.12/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/software/python/2.7.12/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/software/python/2.7.12/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): indices[0,4] = 39344 is not in [0, 20000)
	 [[Node: seq_embedding/embedding_lookup = Gather[Tindices=DT_INT64, Tparams=DT_FLOAT, _class=["loc:@seq_embedding/map"], validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](seq_embedding/map/read, batch_and_pad:1)]]

Traceback (most recent call last):
  File "/gpfs/fs2/scratch/tkhunkhe/MemeCaptcha/models_cnn_lstm/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 117, in <module>
    tf.app.run()
  File "/software/python/2.7.12/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/gpfs/fs2/scratch/tkhunkhe/MemeCaptcha/models_cnn_lstm/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 113, in main
    saver=saver)
  File "/software/python/2.7.12/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 804, in train
    raise
  File "/gpfs/fs1/sfw2/python/2.7.12/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/software/python/2.7.12/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 973, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/software/python/2.7.12/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 801, in stop
    stop_grace_period_secs=self._stop_grace_secs)
  File "/software/python/2.7.12/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 386, in join
    six.reraise(*self._exc_info_to_raise)
  File "/software/python/2.7.12/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 296, in stop_on_exception
    yield
  File "/software/python/2.7.12/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 487, in run
    self.run_loop()
  File "/software/python/2.7.12/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 1003, in run_loop
    self._sv.global_step])
  File "/software/python/2.7.12/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/software/python/2.7.12/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/software/python/2.7.12/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/software/python/2.7.12/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0,4] = 39344 is not in [0, 20000)
	 [[Node: seq_embedding/embedding_lookup = Gather[Tindices=DT_INT64, Tparams=DT_FLOAT, _class=["loc:@seq_embedding/map"], validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](seq_embedding/map/read, batch_and_pad:1)]]

Caused by op u'seq_embedding/embedding_lookup', defined at:
  File "/gpfs/fs2/scratch/tkhunkhe/MemeCaptcha/models_cnn_lstm/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 117, in <module>
    tf.app.run()
  File "/software/python/2.7.12/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/gpfs/fs2/scratch/tkhunkhe/MemeCaptcha/models_cnn_lstm/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 67, in main
    model.build()
  File "/gpfs/fs2/scratch/tkhunkhe/MemeCaptcha/models_cnn_lstm/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/show_and_tell_model.py", line 355, in build
    self.build_seq_embeddings()
  File "/gpfs/fs2/scratch/tkhunkhe/MemeCaptcha/models_cnn_lstm/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/show_and_tell_model.py", line 226, in build_seq_embeddings
    seq_embeddings = tf.nn.embedding_lookup(embedding_map, self.input_seqs)
  File "/software/python/2.7.12/lib/python2.7/site-packages/tensorflow/python/ops/embedding_ops.py", line 111, in embedding_lookup
    validate_indices=validate_indices)
  File "/software/python/2.7.12/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1359, in gather
    validate_indices=validate_indices, name=name)
  File "/software/python/2.7.12/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/software/python/2.7.12/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/software/python/2.7.12/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): indices[0,4] = 39344 is not in [0, 20000)
	 [[Node: seq_embedding/embedding_lookup = Gather[Tindices=DT_INT64, Tparams=DT_FLOAT, _class=["loc:@seq_embedding/map"], validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](seq_embedding/map/read, batch_and_pad:1)]]
```

**Comment by tkhunkhe** [comment]
- neither not loading or loading tensorflow doesn't help fixing the error.

**Comment by tkhunkhe** [comment]
- The code just cannot work with min_word_count=1
- do `module load caffe` and regenerating all TFrecords and word count file helped!
- I think the TFRecords may be bounded with the word_count_file, so you can only use them with one word_count file that you used to generate them I guess.
